export const PET_NAME = "Knot";

/** What Knot says when poked. Friendly, short, never naggy. */
export const PET_LINES: readonly string[] = [
  "Hi there!",
  "You're doing great today.",
  "Remember to drink some water.",
  "Psst — stretch your legs for a minute?",
  "I'm just keeping your seat warm.",
  "Tickles!",
  "Want to see me jump?",
  "Time logs won't fill themselves… but I believe in you.",
  "Try double-clicking me.",
  "Drag me anywhere. I dare you.",
  "Right-click me for options.",
  "Everything is going to be fine.",
];

export const PET_COPY = {
  firstHello: (name: string) => `Hi ${name}! I'm Knot.`,
  wake: "Mmm… I'm up!",
  dizzy: "Whoa — easy!",
  love: "Aww, that's nice.",
  thrown: "Wheee!",
  approve: "Approved!",
  reject: "Noted.",
  undo: "Undone!",
  success: "Done!",
  napping: "Zzz… tap me to wake me.",
  menuTalk: "Say something",
  menuNap: "Take a nap",
  menuWake: "Wake up",
  menuHide: "Hide Knot",
  menuHideHint: "You can bring me back in Settings.",
  cricketSix: ["SIX!", "Out of the park!", "What a shot!"],
  cricketFour: ["FOUR!", "Cracking drive!", "Straight through the gap!"],
  cricketCentury: "Century! Howzat!",
  cricketNets: ["Nets practice…", "Just a quick knock.", "Howzat?"],
  diyaLit: "Shubh Deepavali!",
  cracker: ["Boom!", "Whoosh!", "Look at that one!"],
  crackerPop: ["Pop!", "Anaar!", "Phuljhadi time!"],
  diwaliLines: ["Happy Diwali!", "Light up the day!", "Mithai break?"],
  christmasLines: ["Ho ho ho!", "Merry Christmas!", "Jingle bells…", "Have you been good?"],
  laugh: "Ho ho ho! Do it again!",
  cry: "Waaah! That was a long way down…",
  comfort: "Aww… thank you. Ho ho ho.",
  holi: ["Happy Holi!", "Bura na mano, Holi hai!", "Color me happy!"],
  ariaLabel: "Knot, your WebTrak pet. Press Enter to say hi.",
} as const;
