export const QUICK_ACTION_COPY = {
  title: (requester: string, type: string) => `${type} request from ${requester}`,
  greeting: (name: string) => `Hi ${name}, this is waiting for your decision.`,
  approve: "Approve",
  reject: "Reject",
  rejectReasonLabel: "Reason for rejecting",
  rejectReasonPlaceholder: "Tell them why, so they can act on it",
  rejectConfirm: "Reject request",
  back: "Back",
  approved: "Approved",
  rejected: "Rejected",
  approvedDetail: "They've been told. You can close this tab.",
  rejectedDetail: "They've been told why. You can close this tab.",
  alreadyDecided: "This request has already been decided.",
  alreadyDecidedDetail: "Nothing more to do here.",
  expiredTitle: "This link has expired",
  expiredDetail: "Open WebTrak to review the request.",
  openWebTrak: "Open WebTrak",
  loadError: "We couldn't load this request. Check your connection and try again.",
  retry: "Try again",
  from: "From",
  to: "To",
  halfDay: "Half day",
  reason: "Reason",
  secureNote: "You're deciding as the manager this link was sent to.",
} as const;
